In [ ]:
import pandas as pd 
import numpy as np

In [ ]:
df = pd.read_csv("mercedesbenz.csv")

In [ ]:
df

,ID,y,X0,X1,X2,X3,X4,X5,X6,X8,...,X375,X376,X377,X378,X379,X380,X382,X383,X384,X385
0,0,130.81,k,v,at,a,d,u,j,o,...,0,0,1,0,0,0,0,0,0,0
1,6,88.53,k,t,av,e,d,y,l,o,...,1,0,0,0,0,0,0,0,0,0
2,7,76.26,az,w,n,c,d,x,j,x,...,0,0,0,0,0,0,1,0,0,0
3,9,80.62,az,t,n,f,d,x,l,e,...,0,0,0,0,0,0,0,0,0,0
4,13,78.02,az,v,n,f,d,h,d,n,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4204,8405,107.39,ak,s,as,c,d,aa,d,q,...,1,0,0,0,0,0,0,0,0,0
4205,8406,108.77,j,o,t,d,d,aa,h,h,...,0,1,0,0,0,0,0,0,0,0
4206,8412,109.22,ak,v,r,a,d,aa,g,e,...,0,0,1,0,0,0,0,0,0,0
4207,8415,87.48,al,r,e,f,d,aa,l,u,...,0,0,0,0,0,0,0,0,0,0
4208,8417,110.85,z,r,ae,c,d,aa,g,w,...,1,0,0,0,0,0,0,0,0,0

In [ ]:
len(df['X0'].unique())

47

In [ ]:
len(df['X1'].unique())

27

In [ ]:
len(df['X2'].unique())

44

In [ ]:
df.drop('ID',axis=1, inplace=True)

In [ ]:
y = df['y']

In [ ]:
df.drop('y',axis=1, inplace=True)

In [ ]:
def data_type(data):
    int = 0
    float = 0
    object = 0
    other = 0
    
    for i in data.columns:
        print(f"feature_name {i}:{data[i].dtype}")
        if data[i].dtype == "int32" or data[i].dtype == "int64":
            int = int+1 
        elif data[i].dtype == "float32" or data[i].dtype == "float64":
            float = float+1 
        elif data[i].dtype == "object":
            object = object+1
        
        else:
            other = other+1
            
    print("Data summary")
    print("_------------")
    print("No of integers ",int)
    print("No of  float features",float)
    print('No of object',object)
    print('No of other',other)

In [ ]:
data_type(df)

feature_name X0:object
feature_name X1:object
feature_name X2:object
feature_name X3:object
feature_name X4:object
feature_name X5:object
feature_name X6:object
feature_name X8:object
feature_name X10:int64
feature_name X11:int64
feature_name X12:int64
feature_name X13:int64
feature_name X14:int64
feature_name X15:int64
feature_name X16:int64
feature_name X17:int64
feature_name X18:int64
feature_name X19:int64
feature_name X20:int64
feature_name X21:int64
feature_name X22:int64
feature_name X23:int64
feature_name X24:int64
feature_name X26:int64
feature_name X27:int64
feature_name X28:int64
feature_name X29:int64
feature_name X30:int64
feature_name X31:int64
feature_name X32:int64
feature_name X33:int64
feature_name X34:int64
feature_name X35:int64
feature_name X36:int64
feature_name X37:int64
feature_name X38:int64
feature_name X39:int64
feature_name X40:int64
feature_name X41:int64
feature_name X42:int64
feature_name X43:int64
feature_name X44:int64
feature_name X45:int64
feature_name X46:int64
feature_name X47:int64
feature_name X48:int64
feature_name X49:int64
feature_name X50:int64
feature_name X51:int64
feature_name X52:int64
feature_name X53:int64
feature_name X54:int64
feature_name X55:int64
feature_name X56:int64
feature_name X57:int64
feature_name X58:int64
feature_name X59:int64
feature_name X60:int64
feature_name X61:int64
feature_name X62:int64
feature_name X63:int64
feature_name X64:int64
feature_name X65:int64
feature_name X66:int64
feature_name X67:int64
feature_name X68:int64
feature_name X69:int64
feature_name X70:int64
feature_name X71:int64
feature_name X73:int64
feature_name X74:int64
feature_name X75:int64
feature_name X76:int64
feature_name X77:int64
feature_name X78:int64
feature_name X79:int64
feature_name X80:int64
feature_name X81:int64
feature_name X82:int64
feature_name X83:int64
feature_name X84:int64
feature_name X85:int64
feature_name X86:int64
feature_name X87:int64
feature_name X88:int64
feature_name X89:int64
feature_name X90:int64
feature_name X91:int64
feature_name X92:int64
feature_name X93:int64
feature_name X94:int64
feature_name X95:int64
feature_name X96:int64
feature_name X97:int64
feature_name X98:int64
feature_name X99:int64
feature_name X100:int64
feature_name X101:int64
feature_name X102:int64
feature_name X103:int64
feature_name X104:int64
feature_name X105:int64
feature_name X106:int64
feature_name X107:int64
feature_name X108:int64
feature_name X109:int64
feature_name X110:int64
feature_name X111:int64
feature_name X112:int64
feature_name X113:int64
feature_name X114:int64
feature_name X115:int64
feature_name X116:int64
feature_name X117:int64
feature_name X118:int64
feature_name X119:int64
feature_name X120:int64
feature_name X122:int64
feature_name X123:int64
feature_name X124:int64
feature_name X125:int64
feature_name X126:int64
feature_name X127:int64
feature_name X128:int64
feature_name X129:int64
feature_name X130:int64
feature_name X131:int64
feature_name X132:int64
feature_name X133:int64
feature_name X134:int64
feature_name X135:int64
feature_name X136:int64
feature_name X137:int64
feature_name X138:int64
feature_name X139:int64
feature_name X140:int64
feature_name X141:int64
feature_name X142:int64
feature_name X143:int64
feature_name X144:int64
feature_name X145:int64
feature_name X146:int64
feature_name X147:int64
feature_name X148:int64
feature_name X150:int64
feature_name X151:int64
feature_name X152:int64
feature_name X153:int64
feature_name X154:int64
feature_name X155:int64
feature_name X156:int64
feature_name X157:int64
feature_name X158:int64
feature_name X159:int64
feature_name X160:int64
feature_name X161:int64
feature_name X162:int64
feature_name X163:int64
feature_name X164:int64
feature_name X165:int64
feature_name X166:int64
feature_name X167:int64
feature_name X168:int64
feature_name X169:int64
feature_name X170:int64
feature_name X171:int64
feature_name X172:int64
feature_name X173:int64
feature_name X174:int64
feature_name X175:int64
feature_name X176:int64
feature_name X177:int64
feature_name X178:int64
feature_name X179:int64
feature_name X180:int64
feature_name X181:int64
feature_name X182:int64
feature_name X183:int64
feature_name X184:int64
feature_name X185:int64
feature_name X186:int64
feature_name X187:int64
feature_name X189:int64
feature_name X190:int64
feature_name X191:int64
feature_name X192:int64
feature_name X194:int64
feature_name X195:int64
feature_name X196:int64
feature_name X197:int64
feature_name X198:int64
feature_name X199:int64
feature_name X200:int64
feature_name X201:int64
feature_name X202:int64
feature_name X203:int64
feature_name X204:int64
feature_name X205:int64
feature_name X206:int64
feature_name X207:int64
feature_name X208:int64
feature_name X209:int64
feature_name X210:int64
feature_name X211:int64
feature_name X212:int64
feature_name X213:int64
feature_name X214:int64
feature_name X215:int64
feature_name X216:int64
feature_name X217:int64
feature_name X218:int64
feature_name X219:int64
feature_name X220:int64
feature_name X221:int64
feature_name X222:int64
feature_name X223:int64
feature_name X224:int64
feature_name X225:int64
feature_name X226:int64
feature_name X227:int64
feature_name X228:int64
feature_name X229:int64
feature_name X230:int64
feature_name X231:int64
feature_name X232:int64
feature_name X233:int64
feature_name X234:int64
feature_name X235:int64
feature_name X236:int64
feature_name X237:int64
feature_name X238:int64
feature_name X239:int64
feature_name X240:int64
feature_name X241:int64
feature_name X242:int64
feature_name X243:int64
feature_name X244:int64
feature_name X245:int64
feature_name X246:int64
feature_name X247:int64
feature_name X248:int64
feature_name X249:int64
feature_name X250:int64
feature_name X251:int64
feature_name X252:int64
feature_name X253:int64
feature_name X254:int64
feature_name X255:int64
feature_name X256:int64
feature_name X257:int64
feature_name X258:int64
feature_name X259:int64
feature_name X260:int64
feature_name X261:int64
feature_name X262:int64
feature_name X263:int64
feature_name X264:int64
feature_name X265:int64
feature_name X266:int64
feature_name X267:int64
feature_name X268:int64
feature_name X269:int64
feature_name X270:int64
feature_name X271:int64
feature_name X272:int64
feature_name X273:int64
feature_name X274:int64
feature_name X275:int64
feature_name X276:int64
feature_name X277:int64
feature_name X278:int64
feature_name X279:int64
feature_name X280:int64
feature_name X281:int64
feature_name X282:int64
feature_name X283:int64
feature_name X284:int64
feature_name X285:int64
feature_name X286:int64
feature_name X287:int64
feature_name X288:int64
feature_name X289:int64
feature_name X290:int64
feature_name X291:int64
feature_name X292:int64
feature_name X293:int64
feature_name X294:int64
feature_name X295:int64
feature_name X296:int64
feature_name X297:int64
feature_name X298:int64
feature_name X299:int64
feature_name X300:int64
feature_name X301:int64
feature_name X302:int64
feature_name X304:int64
feature_name X305:int64
feature_name X306:int64
feature_name X307:int64
feature_name X308:int64
feature_name X309:int64
feature_name X310:int64
feature_name X311:int64
feature_name X312:int64
feature_name X313:int64
feature_name X314:int64
feature_name X315:int64
feature_name X316:int64
feature_name X317:int64
feature_name X318:int64
feature_name X319:int64
feature_name X320:int64
feature_name X321:int64
feature_name X322:int64
feature_name X323:int64
feature_name X324:int64
feature_name X325:int64
feature_name X326:int64
feature_name X327:int64
feature_name X328:int64
feature_name X329:int64
feature_name X330:int64
feature_name X331:int64
feature_name X332:int64
feature_name X333:int64
feature_name X334:int64
feature_name X335:int64
feature_name X336:int64
feature_name X337:int64
feature_name X338:int64
feature_name X339:int64
feature_name X340:int64
feature_name X341:int64
feature_name X342:int64
feature_name X343:int64
feature_name X344:int64
feature_name X345:int64
feature_name X346:int64
feature_name X347:int64
feature_name X348:int64
feature_name X349:int64
feature_name X350:int64
feature_name X351:int64
feature_name X352:int64
feature_name X353:int64
feature_name X354:int64
feature_name X355:int64
feature_name X356:int64
feature_name X357:int64
feature_name X358:int64
feature_name X359:int64
feature_name X360:int64
feature_name X361:int64
feature_name X362:int64
feature_name X363:int64
feature_name X364:int64
feature_name X365:int64
feature_name X366:int64
feature_name X367:int64
feature_name X368:int64
feature_name X369:int64
feature_name X370:int64
feature_name X371:int64
feature_name X372:int64
feature_name X373:int64
feature_name X374:int64
feature_name X375:int64
feature_name X376:int64
feature_name X377:int64
feature_name X378:int64
feature_name X379:int64
feature_name X380:int64
feature_name X382:int64
feature_name X383:int64
feature_name X384:int64
feature_name X385:int64
Data summary
_------------
No of integers  368
No of  float features 0
No of object 8
No of other 0

In [ ]:
def distinct_categeries(data):
    for i in data.columns:
        if data[i].dtype == "object":
            print(f"The no of categories in {i}",len(data[i].unique()))
            print(data[i].value_counts())

In [ ]:
distinct_categeries(df)

The no of categories in X0 47
z     360
ak    349
y     324
ay    313
t     306
x     300
o     269
f     227
n     195
w     182
j     181
az    175
aj    151
s     106
ap    103
h      75
d      73
al     67
v      36
af     35
m      34
ai     34
e      32
ba     27
at     25
a      21
ax     19
am     18
aq     18
i      18
u      17
l      16
aw     16
ad     14
k      11
b      11
au     11
r      10
as     10
bc      6
ao      4
c       3
q       2
aa      2
ab      1
g       1
ac      1
Name: X0, dtype: int64
The no of categories in X1 27
aa    833
s     598
b     592
l     590
v     408
r     251
i     203
a     143
c     121
o      82
w      52
z      46
u      37
e      33
m      32
t      31
h      29
y      23
f      23
j      22
n      19
k      17
p       9
g       6
q       3
d       3
ab      3
Name: X1, dtype: int64
The no of categories in X2 44
as    1659
ae     496
ai     415
m      367
ak     265
r      153
n      137
s       94
f       87
e       81
aq      63
ay      54
a       47
t       29
i       25
k       25
b       21
ao      20
ag      19
z       19
d       18
ac      13
g       12
y       11
ap      11
x       10
aw       8
h        6
at       6
al       5
q        5
an       5
p        4
ah       4
av       4
au       3
af       1
j        1
o        1
am       1
ar       1
aa       1
c        1
l        1
Name: X2, dtype: int64
The no of categories in X3 7
c    1942
f    1076
a     440
d     290
g     241
e     163
b      57
Name: X3, dtype: int64
The no of categories in X4 4
d    4205
a       2
c       1
b       1
Name: X4, dtype: int64
The no of categories in X5 29
w     231
v     231
q     220
r     215
s     214
d     214
n     212
p     208
m     208
i     207
ae    205
ag    204
ac    200
ab    197
l     195
af    188
ad    185
k     177
c     131
j     125
aa    112
ah     97
o      20
f       7
x       2
y       1
g       1
h       1
u       1
Name: X5, dtype: int64
The no of categories in X6 12
g    1042
j    1039
d     625
i     488
l     478
a     206
h     190
k      43
c      38
b      28
f      20
e      12
Name: X6, dtype: int64
The no of categories in X8 25
j    277
s    255
f    243
n    242
i    237
e    225
r    219
a    210
w    196
v    194
b    190
k    176
o    163
m    155
g    130
u    119
t    119
q    117
h    117
y    116
x    105
d    103
l    101
p    100
c    100
Name: X8, dtype: int64

In [ ]:
# if any feature in a data set has more than 10 (or) 15 unique categories we refer it as a cardinal data and the problem is termed as 'handaling high' cardinality

In [ ]:
# implementing the first variant (count frequency encoder)
# steps:
# 1. Identify the top  categories with highest occurances
# 2. APPLY one hot encoding on these n categories
#Not: The value of n is sbjective and can be changed to get better results usually value of n is choosen in such a way that it constitute to 80% of the data

In [ ]:
df_copy = df

In [ ]:
def count_frequency_encoder(data):
    for i in data.columns:
        if data[i].dtype == "object":
            top_n = data[i].value_counts().head().index
            for j in top_n:
                data[i+'_'+j] = np.where(data[i] == j,1,0)
            data.drop(i,axis=1,inplace=True)
    return data

In [ ]:
count_frequency_encoder(df)

,X10,X11,X12,X13,X14,X15,X16,X17,X18,X19,...,X6_g,X6_j,X6_d,X6_i,X6_l,X8_j,X8_s,X8_f,X8_n,X8_i
0,0,0,0,1,0,0,0,0,1,0,...,0,1,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,1,0,0,0,0,0
2,0,0,0,0,0,0,0,1,0,0,...,0,1,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4204,0,0,0,0,1,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
4205,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4206,0,0,1,1,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
4207,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
4208,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0

In [ ]:
def encoding_features(ds,n):
    for i in ds.columns:
        if ds[i].dtype == 'object':
            top_n = ds[i].value_counts().head(int(len(ds[i]*(n/100)))).index
            for j in top_n:
                ds[i+'_'+j] = np.where(ds[i] == j,1,0)
            ds.drop(i,axis=1,inplace=True)
    return ds

In [ ]:
encoding_features(df_copy,80)

,X10,X11,X12,X13,X14,X15,X16,X17,X18,X19,...,X6_g,X6_j,X6_d,X6_i,X6_l,X8_j,X8_s,X8_f,X8_n,X8_i
0,0,0,0,1,0,0,0,0,1,0,...,0,1,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,1,0,0,0,0,0
2,0,0,0,0,0,0,0,1,0,0,...,0,1,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4204,0,0,0,0,1,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
4205,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4206,0,0,1,1,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
4207,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
4208,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0